version: '3'
services:
    postgres:
        image: postgres
        env_file:
            - database.env
        volumes:
            - postgres-server-data:/var/lib/postgresql/data/
        expose:
            - "5432"
    computer:
        build: ./computer
        restart: always
        volumes:
            - ./computer/src/app:/home/jon/Desktop/Code/SimpleRecommend/computer

    user_api:
        build: ./user_api
        ports:
            - "8080:8080"
    provider_api:
        build: ./provider_api
        ports:
            - "8081:8080"
    # provider_dashboard:
    #     build: ./provider_dashboard
    #     ports:
    #         - "3001:3001"
    #     stdin_open: true # docker run -i
    #     tty: true        # docker run -t
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true
    #     volumes:
    #         - ./dashboard/src:/app
volumes:
    postgres-server-data:
