version: '3'
services:
    nginx: 
        image: nginx:latest
        container_name: reverse_proxy_one
        restart: unless-stopped
        depends_on:
            - provider-app
            - dashboard
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
          - "80:80"
          - "443:443"
    postgres-server:
        image: postgres
        env_file:
            - database.env
        volumes:
            - postgres-server-data:/var/lib/postgresql/data/
        expose:
            - "5432"
    redis-server:
        image: redis
        ports:
            - "6379"
    computing-app:
        build: ./computer
        restart: always
        volumes:
            - ./computer/src/app:/home/jon/Desktop/Code/SimpleRecommend/computer

    go-app:
        build: ./front_go
        ports:
            - "8080:8080"

    provider-app:
        build: ./provider_area
        ports:
            - "8081:8080"
    dashboard:
        build: ./dashboard
        ports:
            - "3001:3001"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./dashboard/src:/app
volumes:
    postgres-server-data:
